name: Sync University Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Re-author and Push
        env:
          DEST_TOKEN: ${{ secrets.TARGET_REPO_PAT }}
        run: |
          git config user.name "eduing-in"
          git config user.email "eduing-in@users.noreply.github.com"
          git commit --amend --no-edit --reset-author
          git push --force https://eduing-in:${DEST_TOKEN}@github.com/eduing-in/eduing-university.git main:main
